input_dir=G:\My Drive\Peter\Taichi\Confucius4\yang85\edgetts
output_dir=G:\My Drive\Peter\Taichi\Confucius4\yang85\mp3
bitrate=192k
# output_filename=yang85_25min.mp3
# formlength=1500
form=yang85form.properties
intro=normal.mp3
output_filename=yang85_22min.mp3
formlength=1320
