input_dir=G:\My Drive\Peter\Taichi\Confucius4
output_dir=G:\My Drive\Peter\Taichi\Confucius4
bitrate=192k
# Tracklist
42_00.wav=5.0
42_01.wav=10.0
42_02.wav=15.0
42_03.wav=20.0
42_04.wav=25.0
42_05.wav=30.0